import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// For app-wide data that needs to be loaded once when the app starts, you can use the layout.tsx file to fetch and provide the data to the entire application.
// We can move this to Util class
async function fetchInitialJsonData( jsonPathStr: string ): Promise<any> {
  const res = await fetch( jsonPathStr );
  const data = await res.json();
  console.log( "data", data );
  return data;
}


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const periodData = await (await fetch("/data/data.json")).json();

  //const periodData2 = await fetchInitialJsonData( "/data/periods.json" );
  //const locationData = await fetchInitialJsonData( "/data/locations.json" );
  //const valueData = await fetchInitialJsonData( "/data/data.json" );

  // We need to put this on state.
  // console.log( "periodData", periodData );


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
